source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-archives"
gem "jekyll-include-cache"
gem "jekyll-compose"
gem "jekyll-optional-front-matter"